version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: learn-hub-back
    environment:
      - PORT=${PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  
  pqadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - 5050:80